title: FFHS Bsc. Cybersecurity
description: Inhalte aus dem Bsc. Cybersecurity an der FFHS (Start HS23/24)
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
